apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-cicd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-cicd-demo
  template:
    metadata:
      labels:
        app: java-cicd-demo
    spec:
      containers:
      - name: java-cicd-demo
        image: varshithyadav/java-cicd-demo:latest  # This will be replaced dynamically in Jenkins
        ports:
        - containerPort: 9000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
